### ISSUE TITLE
ERROR in ./node_modules/react-pdf-tailwind/dist/index.mjs 

### ISSUE THREAD

**Issue by Baghdad-Hamdoud** [aanckar/react-pdf-tailwind#2]
`ERROR in ./node_modules/react-pdf-tailwind/dist/index.mjs 1:0-54
Module not found: Error: Can't resolve 'tailwindcss/resolveConfig' in 'C:\Users\Baghdad\Desktop\resume\node_modules\react-pdf-tailwind\dist'
Did you mean 'resolveConfig.js'?
BREAKING CHANGE: The request 'tailwindcss/resolveConfig' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
`

**Comment by aanckar** [comment]
Sorry for the late reply - I just published a new version of this package, at least ESM seems to be working for me now.

**Comment by msichterman** [comment]
I am still seeing this issue. Any advice to fix it?

**Comment by Baghdad-Hamdoud** [comment]
I don't remember well, it was 9 month ago and i think i just skipped the issue.

Maybe, like @aanckar said, it has been resolved with last update

**Comment by msichterman** [comment]
I ended up just resolving the path to point to `resolveConfig.js` in my webpack config
