### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by hwb15** [aanckar/react-pdf-tailwind#6]
Hi!

I'm trying to change up the way the `createTw` module is exported so I can use it within the `react-pdf-repl` although can't seem to get a build done?

Getting the following issue, any ideas would be much appreciated?

`
src/index.ts → dist/index.js, dist/index.mjs...
[!] (plugin esbuild) Error: Transform failed with 1 error:
/Users/user/Code/react-pdf-tailwind/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in transform() call: "bundle"`

**Comment by hwb15** [comment]
Sorted by rewriting the rollup.config to:

```import dts from "rollup-plugin-dts";
import esbuild from "rollup-plugin-esbuild";
const pkg = require("./package.json");

const name = pkg.main.replace(/\.js$/, "");

export default [
  {
    input: "src/index.ts",
    external: [
      ...Object.keys(pkg.dependencies || {}),
      ...Object.keys(pkg.peerDependencies || {}),
    ],
    plugins: [
      esbuild({
        include: /\.ts?$/,
        target: "es2017",
      }),
    ],
    output: [
      {
        file: `${name}.js`,
        format: "cjs",
        sourcemap: true,
      },
      {
        file: `${name}.mjs`,
        format: "es",
        sourcemap: true,
      },
    ],
  },
  {
    input: "src/index.ts",
    plugins: [dts()],
    output: {
      file: `${name}.d.ts`,
      format: "es",
    },
  },
];
```

**Comment by aanckar** [comment]
Hi, I just published a new version of this package, where I updated some dependencies and the build process as well (among other things, I removed the apparently now deprecated `bundle` option from esbuild). Could you check if the update works for you (without changing the rollup config)?

**Comment by hwb15** [comment]
Hi @aanckar, I'll test it now - I was going to fork the repo and make changes to the export of createTw so it works within the `react-pdf-repl`, it needs to be a named export instead of export default to work with the repl (https://github.com/jeetiss/react-pdf-repl)

**Comment by hwb15** [comment]
> Hi, I just published a new version of this package, where I updated some dependencies and the build process as well (among other things, I removed the apparently now deprecated `bundle` option from esbuild). Could you check if the update works for you (without changing the rollup config)?

Works as expected now and allows building, I've made the changes to the export and also works great just needs to be imported as: `import { createTw} from 'react-pdf-tailwind'`
